"""Utility functions for VAT with VIME Feature framework."""

import numpy as np
import torch
import json
import os
from datetime import datetime
from sklearn.metrics import accuracy_score, roc_auc_score


def generate_mask(p, x):
    """Generate binary mask matrix."""
    return np.random.binomial(1, p, x.shape)


def corrupt_samples(mask, x):
    """Generate corrupted samples by column-wise shuffling.

    Core formula: tilde_x = m * bar_x + (1-m) * x
    Where bar_x is generated by column-wise shuffling.
    """
    n, dim = x.shape
    x_shuffled = np.array(
        [x[np.random.permutation(n), i] for i in range(dim)]
    ).T
    x_corrupt = x * (1 - mask) + x_shuffled * mask
    return (x != x_corrupt).astype(int), x_corrupt


def evaluate(metric, y_true, y_pred):
    """Evaluate performance."""
    if metric == "acc":
        return accuracy_score(
            np.argmax(y_true, axis=1), np.argmax(y_pred, axis=1)
        )
    elif metric == "auc":
        return roc_auc_score(y_true[:, 1], y_pred[:, 1])


def to_labels(one_hot):
    """Convert one-hot matrix to label vector."""
    return np.argmax(one_hot, axis=1)


def to_one_hot(labels):
    """Convert label vector to one-hot matrix."""
    return np.eye(len(np.unique(labels)))[labels]


def convert_to_serializable(obj):
    """Convert numpy / torch objects into JSON-serializable formats."""
    if isinstance(obj, np.ndarray):
        return obj.tolist()
    if isinstance(obj, np.integer):
        return int(obj)
    if isinstance(obj, np.floating):
        return float(obj)
    if isinstance(obj, dict):
        return {k: convert_to_serializable(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [convert_to_serializable(item) for item in obj]
    if isinstance(obj, torch.Tensor):
        return obj.cpu().numpy().tolist()
    return obj


class EarlyStopping:
    """Early stopping helper."""

    def __init__(self, patience=5, min_delta=0.0):
        self.patience = patience
        self.min_delta = min_delta
        self.best_loss = float("inf")
        self.counter = 0
        self.best_state = None

    def step(self, val_loss, model):
        """Check if should stop and update best model."""
        if val_loss < self.best_loss - self.min_delta:
            self.best_loss = val_loss
            self.counter = 0
            self.best_state = model.state_dict().copy()
            return False
        else:
            self.counter += 1
            return self.counter >= self.patience

    def load_best(self, model):
        """Load best model state."""
        if self.best_state:
            model.load_state_dict(self.best_state)


def log_progress(epoch, max_epochs, train_metrics, val_loss, interval=20):
    """Log training progress."""
    if (epoch + 1) % interval == 0:
        metrics_str = ", ".join(
            f"{k.capitalize()}: {v:.6f}" for k, v in train_metrics.items()
        )
        print(f"  Epoch {epoch+1}/{max_epochs}, {metrics_str}, Val: {val_loss:.6f}")


def log_iteration_progress(iteration, max_iterations, metrics, interval=20):
    """Log iteration progress."""
    if iteration % interval == 0:
        metrics_str = ", ".join(
            f"{k.capitalize()}: {v:.6f}" for k, v in metrics.items()
        )
        print(f"  Iter {iteration}/{max_iterations}, {metrics_str}")


def save_checkpoint(model, path):
    """Save model checkpoint."""
    torch.save(model.state_dict(), path)


def load_checkpoint(model, path, weights_only=True):
    """Load model checkpoint."""
    model.load_state_dict(torch.load(path, weights_only=weights_only))


def save_training_metrics(
    save_dir: str,
    model_name: str,
    model_state_dict: dict,
    training_history: dict = None,
    hyperparameters: dict = None,
    final_metrics: dict = None,
    model_info: dict = None,
    metadata: dict = None,
):
    """Save comprehensive training information including model, metrics, and metadata."""
    os.makedirs(save_dir, exist_ok=True)

    # Save model
    model_path = os.path.join(save_dir, f"{model_name}.pth")
    torch.save(model_state_dict, model_path)

    # Prepare comprehensive metrics dictionary
    metrics_dict = {
        "model_name": model_name,
        "model_path": model_path,
    }

    if training_history is not None:
        metrics_dict["training_history"] = training_history

    if hyperparameters is not None:
        metrics_dict["hyperparameters"] = hyperparameters

    if final_metrics is not None:
        metrics_dict["final_metrics"] = final_metrics

    if model_info is not None:
        metrics_dict["model_info"] = model_info

    if metadata is not None:
        metrics_dict["metadata"] = metadata
    else:
        metrics_dict["metadata"] = {
            "save_timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        }

    metrics_dict = convert_to_serializable(metrics_dict)

    # Save metrics as JSON
    metrics_path = os.path.join(save_dir, f"{model_name}_metrics.json")
    with open(metrics_path, 'w', encoding='utf-8') as f:
        json.dump(metrics_dict, f, indent=2, ensure_ascii=False)

    print(f"  Model saved to: {model_path}")
    print(f"  Metrics saved to: {metrics_path}")

    return model_path, metrics_path


def save_results_summary(summary_path, method_name, method_results, metadata=None):
    """Save or update experiment summary file that aggregates multiple methods."""
    os.makedirs(os.path.dirname(summary_path), exist_ok=True)

    if os.path.exists(summary_path):
        with open(summary_path, "r", encoding="utf-8") as f:
            summary_data = json.load(f)
    else:
        summary_data = {"metadata": {}, "methods": {}}

    if metadata:
        summary_data.setdefault("metadata", {})
        summary_data["metadata"].update(convert_to_serializable(metadata))

    summary_data.setdefault("methods", {})
    summary_data["methods"][method_name] = convert_to_serializable(method_results)

    with open(summary_path, "w", encoding="utf-8") as f:
        json.dump(summary_data, f, indent=2, ensure_ascii=False)

    print(f"  Summary results updated: {summary_path}")
